services:
  - type: web
    name: umpire-analysis
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:server"
    pythonVersion: "3.10.14"
    plan: free
